# Generate dial/needle C sources using LVGL's official LVGLImage.py (bundled with lvgl 9.x).
# Composite PNG is built first via gen_image_data.ps1 (_debug_dial_full.png at native 439).
param(
    [string]$UiRoot = (Join-Path $PSScriptRoot "..\ui"),
    [switch]$DialDebugRedBg = $true,
    [ValidateSet("RGB565", "RGB565A8")]
    [string]$DialCf = "RGB565"
)

$ErrorActionPreference = "Stop"

$PythonCandidates = @(
    "C:\Espressif\tools\python\v6.0.1\venv\Scripts\python.exe",
    "python3",
    "python"
)
$Python = $null
foreach ($candidate in $PythonCandidates) {
    if ($candidate -match '^python') {
        $cmd = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($cmd) {
            $Python = $cmd.Source
            break
        }
    }
    elseif (Test-Path $candidate) {
        $Python = $candidate
        break
    }
}

if (-not $Python) {
    throw "Python not found. Install ESP-IDF Python or add python to PATH."
}

$LvglImagePy = Join-Path $PSScriptRoot "..\firmware\managed_components\lvgl__lvgl\scripts\LVGLImage.py"
if (-not (Test-Path $LvglImagePy)) {
    throw "LVGLImage.py not found at $LvglImagePy - run idf.py build once to fetch lvgl component."
}

& $Python -m pip install pypng lz4 -q 2>$null

Write-Host "Step 1: build composite dial PNG (439x439) via gen_image_data.ps1 ..."
$genArgs = @{
    UiRoot         = $UiRoot
    DialDebugRedBg = $DialDebugRedBg
    DialEmbedPx    = 439
}
& (Join-Path $PSScriptRoot "gen_image_data.ps1") @genArgs | Out-Host

$dialPng = Join-Path $UiRoot "images\_debug_dial_full.png"
$needlePng = Join-Path $UiRoot "images\sc_dial_speed_needle.png"
if (-not (Test-Path $dialPng)) {
    throw "Missing $dialPng - composite step failed."
}

$bg = if ($DialDebugRedBg) { "0xFF0000" } else { "0x1F1F24" }
$cfTag = $DialCf.ToLower()
$suffix = if ($DialDebugRedBg) { "lvgl-439-$cfTag-redbg-debug" } else { "lvgl-439-$cfTag" }

$outDir = Join-Path $UiRoot "images\_lvgl_conv_out"
if (Test-Path $outDir) { Remove-Item $outDir -Recurse -Force }
New-Item -ItemType Directory -Path $outDir | Out-Null

Write-Host ""
Write-Host "Step 2: LVGLImage.py dial ($DialCf, background $bg) ..."
& $Python $LvglImagePy `
    --ofmt=C --cf=$DialCf --compress=NONE `
    --background=$bg `
    -o $outDir `
    --name=dial_speed_dial_data `
    $dialPng -v

Write-Host "Step 2: LVGLImage.py needle (RGB565A8) ..."
& $Python $LvglImagePy `
    --ofmt=C --cf=RGB565A8 --compress=NONE `
    -o $outDir `
    --name=dial_speed_needle_data `
    $needlePng -v

$dialOut = Join-Path $outDir "dial_speed_dial_data.c"
$needleOut = Join-Path $outDir "dial_speed_needle_data.c"
$destDial = Join-Path $UiRoot "images\dial_speed_dial_data.c"
$destNeedle = Join-Path $UiRoot "images\dial_speed_needle_data.c"

Copy-Item $dialOut $destDial -Force
Copy-Item $needleOut $destNeedle -Force
Write-Host "Installed $destDial"
Write-Host "Installed $destNeedle"

# Parse dimensions from generated dial descriptor
$dialSrc = Get-Content $destDial -Raw
$dialW = if ($dialSrc -match '\.w\s*=\s*(\d+)') { [int]$Matches[1] } else { 439 }
$dialH = if ($dialSrc -match '\.h\s*=\s*(\d+)') { [int]$Matches[1] } else { 439 }
$needleBmp = [System.Drawing.Bitmap]::FromFile($needlePng)
try {
    $needleW = $needleBmp.Width
    $needleH = $needleBmp.Height
}
finally {
    $needleBmp.Dispose()
}

$assetsHeader = Join-Path $UiRoot "images\ev_dash_assets.h"
$debugBlock = ""
if (Test-Path $assetsHeader) {
    $prev = Get-Content $assetsHeader -Raw
    if ($prev -match '(?s)/\* Draw-path test solids.*?(?=#endif)') {
        $debugBlock = $Matches[0]
    }
}
$headerWriter = [IO.StreamWriter]::new($assetsHeader, $false, [Text.UTF8Encoding]::new($false))
try {
    $headerWriter.WriteLine('/* Generated by tools/gen_image_data_lvgl.ps1 - do not edit */')
    $headerWriter.WriteLine('#ifndef EV_DASH_ASSETS_H')
    $headerWriter.WriteLine('#define EV_DASH_ASSETS_H')
    $headerWriter.WriteLine('')
    $headerWriter.WriteLine("#define EV_DASH_DIAL_DISPLAY_W $dialW")
    $headerWriter.WriteLine("#define EV_DASH_DIAL_DISPLAY_H $dialH")
    $headerWriter.WriteLine("#define EV_DASH_DIAL_EMBED_W $dialW")
    $headerWriter.WriteLine("#define EV_DASH_DIAL_EMBED_H $dialH")
    $headerWriter.WriteLine("#define EV_DASH_DIAL_W $dialW")
    $headerWriter.WriteLine("#define EV_DASH_DIAL_H $dialH")
    $headerWriter.WriteLine("#define EV_DASH_DIAL_CF `"$DialCf`"")
    $headerWriter.WriteLine("#define EV_DASH_NEEDLE_W $needleW")
    $headerWriter.WriteLine("#define EV_DASH_NEEDLE_H $needleH")
    $headerWriter.WriteLine("#define EV_DASH_ASSETS_ID `"$suffix`"")
    $headerWriter.WriteLine('')
    if ($debugBlock) {
        $headerWriter.WriteLine($debugBlock.TrimEnd())
        $headerWriter.WriteLine('')
    }
    $headerWriter.WriteLine('#endif')
    $headerWriter.WriteLine('')
}
finally {
    $headerWriter.Close()
}

Write-Host "Generated $assetsHeader (id=$suffix)"
Write-Host ""
Write-Host "Flash: cd firmware; idf.py fullclean build flash monitor"
Write-Host ("Serial should show: id={0} dial={1}x{2}" -f $suffix, $dialW, $dialH)
