set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/gauge_center_readout/gauge_center_readout_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/speed_scale_ring/speed_scale_ring_fine_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/speed_scale_ring/speed_scale_ring_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/speedometer/speedometer_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ev_dash_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ev_dash.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_display_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_heading_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_small_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/dial_speed_dial_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/dial_speed_needle_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/debug_img_100_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/debug_img_439_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/debug_img_439_rgb565_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_main_gen.c)